### ISSUE TITLE
How can I connect to web3?

### ISSUE THREAD

**Issue by LouisDouglas** [devlouis98/ETHDivide#2]
I have a problem. How can I connect to meta mask ? what's the web3?

**Comment by devlouis98** [comment]
You can use it in your project
import { useWeb3React } from "@web3-react/core";
import { InjectedConnector } from "@web3-react/injected-connector";

The term "Web3" was coined by Polkadot founder and Ethereum co-founder Gavin Wood in 2014, referring to a "decentralized online ecosystem based on blockchain.
